(function (root, factory) {
  'use strict';
  if (typeof define === 'function' && define.amd) {
    define(factory);
  } else if (typeof exports === 'object') {
    module.exports = factory();
  } else {
    root.Domains = factory();
  }
}(this, function () {
  'use strict';

  const Domains = {
    _allowedDomains: {
      "asm.org": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.asm\.org\/content\/[a-z0-9\-\.\_\/]+`],
      "academic.oup.com": [String.raw`^(http[s]?:\/\/){0,1}academic\.oup\.com\/[a-z]+\/(advance\-)?article(\-abstract)?\/[a-z0-9\/\.\-\_]+`],
      "academicjournals.org": [String.raw`^(http[s]?:\/\/){0,1}academicjournals\.org\/[a-z\/\-]+abstract[a-z0-9\/\.\%\-\_]+`],
      "access.portico.org": [String.raw`^(http[s]?:\/\/){0,1}([a-z0-9]+\.)?portico\.org\/[a-z]+\/\#\![a-z]+\/tab\=pdf`],
      "biomedcentral.com": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.biomedcentral\.com\/articles\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "actascientific.com": [String.raw`^(http[s]?:\/\/){0,1}actascientific\.com\/[a-z]{4}\/pdf\/[a-z]{4}\-[0-9]{2}\-[0-9]{4}\.pdf`],
      "bmj.com": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]*bmj\.com\/content\/[a-z0-9\-\.\_\/]+`],
      "scitation.org": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.scitation\.org\/doi(\/[a-z]+)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "ajmb.umsha.ac.ir": [String.raw`^(http[s]?:\/\/){0,1}ajmb\.umsha\.ac\.ir\/abstract\/[a-z]{4}\-[0-9]+`],
      "psychiatryonline.org": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.psychiatryonline\.org\/doi(\/[a-z]+)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "ajph.aphapublications.org": [String.raw`^(http[s]?:\/\/){0,1}ajph\.aphapublications\.org\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "ajpp.in": [String.raw`^(http[s]?:\/\/){0,1}ajpp\.in\/uploaded\/[a-z0-9]+\.pdf`],
      "akademiai.com": [String.raw`^(http[s]?:\/\/){0,1}akademiai\.com\/doi\/(abs\/)?10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "annals.math.princeton.edu": [String.raw`^(http[s]?:\/\/){0,1}annals\.math\.princeton\.edu\/[0-9]{4}\/[0-9]+\-[0-9]+\/[a-z0-9]+`],
      "annals.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?annals\.org\/aim\/(article\-abstract|fullarticle)\/`],
      "api.elsevier.com": [
        String.raw`^(http[s]?:\/\/){0,1}api\.elsevier\.com\/content\/article\/pii\/[a-z0-9]+`,
        String.raw`^(http[s]?:\/\/){0,1}api\.elsevier\.com\/content\/abstract\/scopus\_id\/[0-9]+`
      ],
      "apsjournals.apsnet.org": [String.raw`^(http[s]?:\/\/){0,1}apsjournals\.apsnet\.org\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "iiarjournals.org": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.iiarjournals\.org\/content\/[0-9]+\/[0-9]+\/[a-z0-9\.]+`],
      "arc.aiaa.org": [String.raw`^(http[s]?:\/\/){0,1}arc\.aiaa\.org\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "arccjournals.com": [String.raw`^(http[s]?:\/\/){0,1}arccjournals\.com\/journal\/[a-z0-9\-]+\/[a-z0-9\-]+`],
      "sciendo.com": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.sciendo\.com\/view\/journals\/[a-z]+\/[0-9]+\/[0-9]+\/article\-[a-z0-9]+\.xml`],
      "article.sapub.org": [String.raw`^(http[s]?:\/\/){0,1}article\.sapub\.org\/10[.][0-9]{4,}(?:[.][0-9]+)*(?:(?!["&\'<>])\S)+\.html`],
      "ascelibrary.org": [String.raw`^(http[s]?:\/\/){0,1}ascelibrary\.org\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "ascopubs.org": [String.raw`^(http[s]?:\/\/){0,1}ascopubs\.org\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "ashpublications.org": [
        String.raw`^(http[s]?:\/\/){0,1}ashpublications\.org\/blood(advances)?\/article\/([0-9]+\/){4}[a-z0-9\-\%]+`,
        String.raw`^(http[s]?:\/\/){0,1}ashpublications\.org\/cgi\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`
      ],
      "asmedigitalcollection.asme.org": [String.raw`^(http[s]?:\/\/){0,1}asmedigitalcollection\.asme\.org\/[a-z]+\/[a-z\-]+\/([0-9]+\/){4}[a-z0-9\-]+`],
      "autosoftjournal.net": [String.raw`^(http[s]?:\/\/){0,1}autosoftjournal\.net\/paperShow\.php\?paper\=`],
      "benjamins.com": [String.raw`^(http[s]?:\/\/){0,1}benjamins\.com\/catalog\/(?:(?!["&\'<>])\S)+`],
      "benthamopen.com": [String.raw`^(http[s]?:\/\/){0,1}benthamopen\.com\/abstract\/[a-z0-9\-]+`],
      "biocoreopen.org": [String.raw`^(http[s]?:\/\/){0,1}biocoreopen\.org\/[a-z]+\/[a-z0-9\-]+\.php`],
      "biomedres.us": [String.raw`^(http[s]?:\/\/){0,1}biomedres\.us\/fulltexts\/[a-z0-9\.]+\.php`],
      "bioone.org": [String.raw`^(http[s]?:\/\/){0,1}bioone\.org\/journals\/[a-z\-]+\/volume\-[0-9]+\/issue\-[0-9]+\/[a-z0-9\.\-\%\(\)]+\/[a-z0-9\-]+\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+(\.[a-z])?`],
      "biopolymers.org.ua": [String.raw`^(http[s]?:\/\/){0,1}biopolymers\.org\.ua\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "biopublisher.ca": [String.raw`^(http[s]?:\/\/){0,1}biopublisher\.ca\/index\.php\/[a-z]+\/article\/[a-z]+\/[0-9]+`],
      "bjgp.org": [String.raw`^(http[s]?:\/\/){0,1}bjgp\.org\/content(\/[0-9]+){2}\/[a-z0-9]+`],
      "brill.com": [String.raw`^(http[s]?:\/\/){0,1}brill\.com\/view\/journals\/[a-z]+(\/[0-9]+){2}\/article\-[a-z0-9\_]+\.xml`],
      "aacrjournals.org": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.aacrjournals\.org\/content\/[a-z0-9\-\_\/]+`],
      "diabetesjournals.org": [
        String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.diabetesjournals\.org\/content\/[0-9]+\/[0-9]+\/[0-9]+`,
        String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.diabetesjournals\.org(\/[a-z]+)?\/doi(\/[a-z]+)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`
      ],
      "chemrxiv.org": [String.raw`^(http[s]?:\/\/){0,1}chemrxiv\.org\/articles\/[a-z0-9\-\_]+(\/[0-9]+){1,}`],
      "clutejournals.com": [String.raw`^(http[s]?:\/\/){0,1}clutejournals\.com\/index\.php\/[a-z]+\/article\/[a-z]+(\/[0-9]+){1,}`],
      "columella.mkk.szie.hu": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?columella\.mkk\.szie\.hu\/archives\/columella(\_[0-9]+){2}\/[a-z0-9\-\_\(\)\%]+\.pdf`],
      "content.iospress.com": [String.raw`^(http[s]?:\/\/){0,1}content\.iospress\.com\/articles\/[a-z\-]+\/[a-z0-9]+`],
      "content.the-jci.org": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.the\-jci\.org\/articles\/view\/[0-9]+`],
      "cshlp.org": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.cshlp\.org\/content\/[a-z0-9\-\_\/\.]+`],
      "plos.org": [
        String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.plos\.org(\/[a-z]+)?\/article\?id\=10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`,
        String.raw`^(http[s]?:\/\/){0,1}([a-z0-9]+\.)?plos\.org\/outbreaks\/article\/[a-z0-9\-]+`
      ],
      "datascience.codata.org": [String.raw`^(http[s]?:\/\/){0,1}datascience\.codata\.org\/articles\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+(\/)?`],
      "dergipark.org.tr": [String.raw`^(http[s]?:\/\/){0,1}dergipark\.org\.tr\/([a-z]+\/){2,}issue(\/[0-9]+){2}`],
      "dl.acm.org": [String.raw`^(http[s]?:\/\/){0,1}dl\.acm\.org\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "aspetjournals.org": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.aspetjournals\.org\/content\/[a-z0-9\-\_\/\.]+`],
      "apa.org": [
        String.raw`^(http[s]?:\/\/){0,1}([a-z]+\.)?apa\.org\/doiLanding\?doi\=10[.][0-9]{4,}(?:[.][0-9]+)*`,
        String.raw`^(http[s]?:\/\/){0,1}([a-z]+\.)?apa\.org\/(journals|record)\/[a-z0-9\/]+`
      ],
      "dspace.lib.cranfield.ac.uk": [String.raw`^(http[s]?:\/\/){0,1}dspace\.lib\.cranfield\.ac\.uk\/handle(\/[0-9]+){1,}`],
      "dsq-sds.org": [String.raw`^(http[s]?:\/\/){0,1}dsq\-sds\.org\/[a-z]+\/view\/[0-9]+`],
      "dx.doi.org": [String.raw`^(http[s]?:\/\/){0,1}dx\.doi\.org\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "e-medjournal.com": [String.raw`^(http[s]?:\/\/){0,1}e\-medjournal\.com\/index\.php(\/[a-z]+){3}\/[0-9]+`],
      "ebooks.iospress.nl": [String.raw`^(http[s]?:\/\/){0,1}ebooks\.iospress\.nl\/publication\/[0-9]+`],
      "ecocyb.ase.ro": [String.raw`^(http[s]?:\/\/){0,1}ecocyb\.ase\.ro\/[a-z0-9\_]+\/[a-z0-9\%\-\(\)]+\.pdf`],
      "econtent.hogrefe.com": [String.raw`^(http[s]?:\/\/){0,1}econtent\.hogrefe\.com\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "edworkingpapers.com": [String.raw`^(http[s]?:\/\/){0,1}edworkingpapers\.com\/[a-z0-9\-]+`],
      "ehe.pitt.edu": [String.raw`^(http[s]?:\/\/){0,1}ehe\.pitt\.edu\/[a-z]+\/index\.php\/[a-z]+\/article\/[a-z]+\/[0-9]+`],
      "ehp.niehs.nih.gov": [String.raw`^(http[s]?:\/\/){0,1}ehp\.niehs\.nih\.gov\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "bioscientifica.com": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.bioscientifica\.com\/view\/journals\/[a-z0-9\-\_\/\.]+\.xml`],
      "ejmr.org": [String.raw`^(http[s]?:\/\/){0,1}ejmr\.org\/ahead\-print\/[a-z0-9\%\,]+\.pdf`],
      "ekja.org": [String.raw`^(http[s]?:\/\/){0,1}ekja\.org\/[a-z]+\/view\.php\?doi\=10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "ekjm.org": [String.raw`^(http[s]?:\/\/){0,1}ekjm\.org\/[a-z]+\/view\.php\?doi\=10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "elifesciences.org": [String.raw`^(http[s]?:\/\/){0,1}elifesciences\.org\/articles\/[0-9]+`],
      "engine.scichina.com": [String.raw`^(http[s]?:\/\/){0,1}engine\.scichina\.com\/publisher\/[a-z]+\/journal\/[a-z]+\/[0-9]+\/[0-9]+\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "epress.lib.uts.edu.au": [String.raw`^(http[s]?:\/\/){0,1}epress\.lib\.uts\.edu\.au\/journals\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "erj.ersjournals.com": [String.raw`^(http[s]?:\/\/){0,1}erj\.ersjournals\.com\/content(\/[0-9]+){3}`],
      "f1000.com": [String.raw`^(http[s]?:\/\/){0,1}f1000\.com\/prime\/[0-9]+(\#[a-z0-9]+)?`],
      "f1000research.com": [String.raw`^(http[s]?:\/\/){0,1}f1000research\.com\/articles\/[0-9\-]+\/v[0-9]+`],
      "figshare.com": [String.raw`^(http[s]?:\/\/){0,1}figshare\.com\/articles\/[a-z\_]+\/[0-9]+`],
      "focsci.com": [String.raw`^(http[s]?:\/\/){0,1}focsci\.com\/archive\/article\/[0-9]+`],
      "foodandnutritionresearch.net": [String.raw`^(http[s]?:\/\/){0,1}foodandnutritionresearch\.net\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "amegroups.com": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.amegroups\.com\/article\/view\/[0-9]+\/[0-9]+`],
      "gsconlinepress.com": [String.raw`^(http[s]?:\/\/){0,1}gsconlinepress\.com\/journals(\/[a-z]+){1,}\/[0-9]+`],
      "hepatmon.com": [String.raw`^(http[s]?:\/\/){0,1}hepatmon\.com(\/[a-z]+){1,}\/articles\/[0-9]+\.html`],
      "horizonepublishing.com": [String.raw`^(http[s]?:\/\/){0,1}horizonepublishing\.com\/journals\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "tbzmed.ac.ir": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.tbzmed\.ac\.ir\/article\/[a-z]+\-[0-9]+`],
      "ibj.pasteur.ac.ir": [String.raw`^(http[s]?:\/\/){0,1}ibj\.pasteur\.ac\.ir\/[a-z0-9\-]+\.html`],
      "ieeexplore.ieee.org": [String.raw`^(http[s]?:\/\/){0,1}ieeexplore\.ieee\.org\/document\/[0-9]+`],
      "ijarbs.com": [String.raw`^(http[s]?:\/\/){0,1}ijarbs\.com\/pdfcopy\/[a-z]+[0-9]+\/[a-z0-9]+\.pdf`],
      "ijme.in": [String.raw`^(http[s]?:\/\/){0,1}ijme\.in\/articles\/[a-z0-9\-]+`],
      "jci.org": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.jci\.org\/articles\/view\/[0-9]+`],
      "insights.ovid.com": [String.raw`^(http[s]?:\/\/){0,1}insights\.ovid\.com\/article\/[0-9\-]+`],
      "intarchmed.com": [String.raw`^(http[s]?:\/\/){0,1}intarchmed\.com+`],
      "iopscience.iop.org": [String.raw`^(http[s]?:\/\/){0,1}iopscience\.iop\.org\/article\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "arvojournals.org": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.arvojournals\.org\/article\.aspx\?articleid\=[0-9]+`],
      "isegoria.revistas.csic.es": [String.raw`^(http[s]?:\/\/){0,1}isegoria\.revistas\.csic\.es\/index\.php\/[a-z]+\/article\/view(\/[0-9]+){1,}`],
      "jamanetwork.com": [String.raw`^(http[s]?:\/\/){0,1}jamanetwork\.com\/journals\/jama([a-z]+)?\/(article\-abstract|fullarticle)\/[0-9]+`],
      "jaoa.org": [String.raw`^(http[s]?:\/\/){0,1}jaoa\.org\/article\.aspx\?articleid\=`],
      "jasn.asnjournals.org": [String.raw`^(http[s]?:\/\/){0,1}jasn\.asnjournals\.org\/content(\/[0-9]+){3}`],
      "biologists.org": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.biologists\.org\/content\/[a-z0-9\-\_\/\.]+`],
      "jddtonline.info": [String.raw`^(http[s]?:\/\/){0,1}jddtonline\.info\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "jhr.pensoft.net": [String.raw`^(http[s]?:\/\/){0,1}jhr\.pensoft\.net\/articles\.php\?id\=`],
      "jhrba.com": [String.raw`^(http[s]?:\/\/){0,1}jhrba\.com\/en\/articles\/[0-9]+\.html`],
      "jjmicrobiol.com": [String.raw`^(http[s]?:\/\/){0,1}jjmicrobiol\.com\/en\/articles\/[0-9]+\.html`],
      "jlsc-pub.org": [String.raw`^(http[s]?:\/\/){0,1}jlsc\-pub\.org\/articles\/abstract\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "jnm.snmjournals.org": [String.raw`^(http[s]?:\/\/){0,1}jnm\.snmjournals\.org\/content(\/[0-9]+){3}`],
      "jnsfsl.sljol.info": [String.raw`^(http[s]?:\/\/){0,1}jnsfsl\.sljol\.info\/articles\/abstract\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "journal.houstonmethodist.org": [String.raw`^(http[s]?:\/\/){0,1}journal\.houstonmethodist\.org\/doi\/abs\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "journal.sajc.org": [String.raw`^(http[s]?:\/\/){0,1}journal\.sajc\.org\/article\.asp\?`],
      "journal.waocp.org": [String.raw`^(http[s]?:\/\/){0,1}journal\.waocp\.org\/article\_[0-9]+\.html`],
      "springeropen.com": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.springeropen\.com\/articles\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "journals.ametsoc.org": [String.raw`^(http[s]?:\/\/){0,1}journals\.ametsoc\.org\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "journals.aom.org": [String.raw`^(http[s]?:\/\/){0,1}journals\.aom\.org\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "journals.aps.org": [String.raw`^(http[s]?:\/\/){0,1}journals\.aps\.org\/[a-z]+\/abstract\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "journals.ashs.org": [String.raw`^(http[s]?:\/\/){0,1}journals\.ashs\.org\/[a-z]+\/view\/journals\/[a-z0-9\.\/\-]+\/article\-[a-z0-9\.\-]+\.xml`],
      "journals.copmadrid.org": [String.raw`^(http[s]?:\/\/){0,1}journals\.copmadrid\.org(\/[a-z]+){1,}\/[a-z0-9]+`],
      "iucr.org": [
        String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.iucr\.org\/[a-z]+\/issues\/[0-9]{4}\/[0-9]{2}\/[0-9]{2}\/[a-z0-9]+\/index\.html`,
        String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.iucr\.org\/cgi-bin\/paper\?[a-z0-9]+`
      ],
      "journals.jcu.edu.au": [String.raw`^(http[s]?:\/\/){0,1}journals\.jcu\.edu\.au\/[a-z]+\/article\/view\/[0-9]+`],
      "journals.lww.com": [String.raw`^(http[s]?:\/\/){0,1}journals\.lww\.com\/[a-z\-]+\/abstract\/[a-z]+\/[a-z\_]+\.[0-9]+\.aspx`],
      "journals.pan.pl": [String.raw`^(http[s]?:\/\/){0,1}journals\.pan\.pl\/[a-z]+\/publication\/[0-9]+\/edition\/[0-9]+\/content`],
      "sagepub.com": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.sagepub\.com(\/[a-z]+)?\/doi(\/[a-z]+)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "journals.tubitak.gov.tr": [String.raw`^(http[s]?:\/\/){0,1}journals\.tubitak\.gov\.tr\/[a-z]+\/issues(\/[a-z0-9\-]+){2}\.pdf`],
      "journals.uic.edu": [String.raw`^(http[s]?:\/\/){0,1}journals\.uic\.edu\/[a-z]+\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "journals.vgtu.lt": [String.raw`^(http[s]?:\/\/){0,1}journals\.vgtu\.lt\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "journals.viamedica.pl": [String.raw`^(http[s]?:\/\/){0,1}journals\.viamedica\.pl\/[a-z\_]+\/article\/view\/[0-9]+`],
      "jspp.psychopen.eu": [String.raw`^(http[s]?:\/\/){0,1}jspp\.psychopen\.eu\/article\/view\/[0-9]+`],
      "juniperpublishers.com": [String.raw`^(http[s]?:\/\/){0,1}juniperpublishers\.com\/[a-z]+\/[a-z\.]+[0-9]+\.php`],
      "jvat.org": [],
      "komejournal.com": [String.raw`^(http[s]?:\/\/){0,1}komejournal\.com\/files\/[a-z\_]+\.pdf`],
      "koreascience.or.kr": [String.raw`^(http[s]?:\/\/){0,1}koreascience\.or\.kr\/article\/[a-z0-9]+\.page`],
      "le.uwpress.org": [String.raw`^(http[s]?:\/\/){0,1}le\.uwpress\.org\/content(\/[0-9]+){3}`],
      "lebs.hbesj.org": [String.raw`^(http[s]?:\/\/){0,1}lebs\.hbesj\.org\/index\.php\/[a-z]+\/article\/view\/[a-z0-9\.]+`],
      "link.springer.com": [
        String.raw`^(http[s]?:\/\/){0,1}link\.springer\.com\/[a-z]+\/10[.][0-9]{4,}(?:[.][0-9]+)*(\/|\%2f)(?:(?!["&\'<>])\S)+`,
        String.raw`^(http[s]?:\/\/){0,1}link\.springer\.com\/[a-z]+\/[0-9]+`
      ],
      "linkinghub.elsevier.com": [String.raw`^(http[s]?:\/\/){0,1}linkinghub\.elsevier\.com\/retrieve\/pii\/[a-z0-9]+`],
      "lupinepublishers.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?lupinepublishers\.com\/[a-z\-]+\/fulltext\/[a-z\-]+\.id\.[0-9]+\.php`],
      "madridge.org": [String.raw`^(http[s]?:\/\/){0,1}madridge\.org\/[a-z\-]+\/[a-z]+\-[0-9]+\.php`],
      "medcraveonline.com": [String.raw`^(http[s]?:\/\/){0,1}medcraveonline\.com\/jpcpy\/[a-z\-]+\.html`],
      "jmir.org": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.jmir\.org\/[0-9]+\/[0-9]+\/[a-z0-9]+`],
      "medwelljournals.com": [String.raw`^(http[s]?:\/\/){0,1}medwelljournals\.com\/abstract\/\?doi\=`],
      "mem.lyellcollection.org": [String.raw`^(http[s]?:\/\/){0,1}mem\.lyellcollection\.org\/content(\/[0-9]+){2}\/[a-z]+\.[0-9]+`],
      "metapress.com": [String.raw`^(http[s]?:\/\/){0,1}metapress\.com\/\?genre\=article\&id\=doi`],
      "mr.crossref.org": [String.raw`^(http[s]?:\/\/){0,1}mr\.crossref\.org\/iPage\?doi\=`],
      "muse.jhu.edu": [String.raw`^(http[s]?:\/\/){0,1}muse\.jhu\.edu\/article\/[0-9]+`],
      "neurology.org": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.neurology\.org\/content(\/[a-z]+)?\/[0-9]+\/[0-9]+\/([0-9]+\/)?[a-z0-9\.]+`],
      "hindawi.com": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.hindawi\.com\/journals\/[a-z]+\/[0-9]{4}\/[0-9]+\/`],
      "nobleresearch.org": [String.raw`^(http[s]?:\/\/){0,1}nobleresearch\.org\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "nv.nltu.edu.ua": [String.raw`^(http[s]?:\/\/){0,1}nv\.nltu\.edu\.ua\/index\.php\/journal\/article\/view\/[0-9]+`],
      "oatext.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?oatext\.com\/[a-z0-9\-]+\.php`],
      "ojs.jmolekul.com": [String.raw`^(http[s]?:\/\/){0,1}ojs\.jmolekul\.com\/ojs\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "ojs.lib.unideb.hu": [String.raw`^(http[s]?:\/\/){0,1}ojs\.lib\.unideb\.hu\/[a-z]+\/article\/view\/[0-9]+`],
      "ojs.ptbioch.edu.pl": [String.raw`^(http[s]?:\/\/){0,1}ojs\.ptbioch\.edu\.pl\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "online.boneandjoint.org.uk": [String.raw`^(http[s]?:\/\/){0,1}online\.boneandjoint\.org\.uk\/doi\/full\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "onlinelibrary.wiley.com": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]*onlinelibrary\.wiley\.com\/doi\/[a-z]+\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "opastonline.com": [String.raw`^(http[s]?:\/\/){0,1}opastonline\.com\/wp\-content\/uploads(\/[0-9]+){2}\/[a-z0-9\-]+\.pdf`],
      "openneurologyjournal.com": [String.raw`^(http[s]?:\/\/){0,1}openneurologyjournal\.com\/volume\/[0-9]+\/page\/[0-9]+`],
      "ortopedia.com.pl": [String.raw`^(http[s]?:\/\/){0,1}ortopedia\.com\.pl\/resources\/html\/article\/details\?id\=`],
      "osf.io": [String.raw`^(http[s]?:\/\/){0,1}osf\.io\/[a-z0-9]+`],
      "pagepressjournals.org": [String.raw`^(http[s]?:\/\/){0,1}pagepressjournals\.org\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "paleorxiv.org": [String.raw`^(http[s]?:\/\/){0,1}paleorxiv\.org\/[a-z0-9]+`],
      "papers.ssrn.com": [String.raw`^(http[s]?:\/\/){0,1}papers\.ssrn\.com\/[a-z0-9]+\/papers\.cfm\?abstract\_id\=`],
      "pediatrics.aappublications.org": [String.raw`^(http[s]?:\/\/){0,1}pediatrics\.aappublications\.org\/content\/[0-9]+\/[a-z0-9\_]+\/[a-z0-9\.]+`],
      "peerj.com": [String.raw`^(http[s]?:\/\/){0,1}peerj\.com\/(preprints|articles)\/[a-z0-9]+`],
      "periodicos.uem.br": [String.raw`^(http[s]?:\/\/){0,1}periodicos\.uem\.br\/[a-z]+\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "pjms.com.pk": [String.raw`^(http[s]?:\/\/){0,1}pjms\.com(\.pk)?\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "portlandpress.com": [String.raw`^(http[s]?:\/\/){0,1}portlandpress\.com\/[a-z]+\/(article\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+|article\-abstract(\/[0-9]+){3})\/[0-9]+\/[a-z0-9\-\%]`],
      "pp.bme.hu": [String.raw`^(http[s]?:\/\/){0,1}pp\.bme\.hu\/[a-z]+\/article\/view\/[0-9]+`],
      "projecteuclid.org": [String.raw`^(http[s]?:\/\/){0,1}projecteuclid\.org\/[a-z0-9\.]+\/[0-9]+`],
      "protocolexchange.researchsquare.com": [String.raw`^(http[s]?:\/\/){0,1}protocolexchange\.researchsquare\.com\/article\/[a-z0-9\-]+\/[a-z0-9]+`],
      "przyrbwn.icm.edu.pl": [String.raw`^(http[s]?:\/\/){0,1}przyrbwn\.icm\.edu\.pl\/app\/pdf\/[0-9]+\/[a-z0-9]+\.pdf`],
      "psyarxiv.com": [String.raw`^(http[s]?:\/\/){0,1}psyarxiv\.com\/[a-z0-9]+`],
      "publishing.rcseng.ac.uk": [String.raw`^(http[s]?:\/\/){0,1}publishing\.rcseng\.ac\.uk\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "pubs.acs.org": [String.raw`^(http[s]?:\/\/){0,1}pubs\.acs\.org\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "pubs.er.usgs.gov": [String.raw`^(http[s]?:\/\/){0,1}pubs\.er\.usgs\.gov\/publication\/[a-z0-9]+`],
      "pubs.lib.umn.edu": [String.raw`^(http[s]?:\/\/){0,1}pubs\.lib\.umn\.edu\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "pubs.rsc.org": [String.raw`^(http[s]?:\/\/){0,1}pubs\.rsc\.org\/[a-z]+\/content\/articlelanding\/[0-9]+\/[a-z]+\/[a-z0-9]+(\#\!divabstract)?`],
      "pubs.rsna.org": [String.raw`^(http[s]?:\/\/){0,1}pubs\.rsna\.org\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "pubsonline.informs.org": [String.raw`^(http[s]?:\/\/){0,1}pubsonline\.informs\.org\/doi(\/abs)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "revistas.inia.es": [String.raw`^(http[s]?:\/\/){0,1}revistas\.inia\.es\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "revistas.um.es": [String.raw`^(http[s]?:\/\/){0,1}revistas\.um\.es\/[a-z]+\/article\/view\/[0-9]+`],
      "riviste.unimi.it": [String.raw`^(http[s]?:\/\/){0,1}riviste\.unimi\.it\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "rmm.mazums.ac.ir": [String.raw`^(http[s]?:\/\/){0,1}rmm\.mazums\.ac\.ir\/article\-[a-z0-9\-]+\.html`],
      "royalsocietypublishing.org": [String.raw`^(http[s]?:\/\/){0,1}royalsocietypublishing\.org\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "rupress.org": [String.raw`^(http[s]?:\/\/){0,1}rupress\.org\/[a-z]+\/article(\/[0-9]+){4}\/[a-z0-9\-\%]`],
      "sajbm.org": [String.raw`^(http[s]?:\/\/){0,1}sajbm\.org\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "scialert.net": [String.raw`^(http[s]?:\/\/){0,1}scialert\.net\/abstract\/\?doi\=`],
      "scielo.conicyt.cl": [String.raw`^(http[s]?:\/\/){0,1}scielo\.conicyt\.cl\/scielo\.php\?`],
      "scielo.isciii.es": [String.raw`^(http[s]?:\/\/){0,1}scielo\.isciii\.es\/scielo\.php\?`],
      "sistemas.uft.edu.br": [String.raw`^(http[s]?:\/\/){0,1}sistemas\.uft\.edu\.br\/[a-z]+\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "standardsingenomics.org": [String.raw`^(http[s]?:\/\/){0,1}standardsingenomics\.org\/content(\/[0-9]+){3}`],
      "surgicalneurologyint.com": [String.raw`^(http[s]?:\/\/){0,1}surgicalneurologyint\.com\/[a-z\-]+\/[a-z0-9\-]+`],
      "synapse.koreamed.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?synapse\.koreamed\.org\/doix\.php\?id\=`],
      "thejns.org": [String.raw`^(http[s]?:\/\/){0,1}thejns\.org(\/[a-z]+)?\/view\/journals\/j\-neurosurg(\-[a-z]+)?(\/[0-9]+){2}\/article\-[a-z0-9]+\.xml`],
      "theoryandpractice.citizenscienceassociation.org": [String.raw`^(http[s]?:\/\/){0,1}theoryandpractice\.citizenscienceassociation\.org\/articles\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "thewinnower.com": [String.raw`^(http[s]?:\/\/){0,1}thewinnower\.com\/(\/)?(papers|discussions)\/[a-z0-9\-]+`],
      "tidsskriftet.no": [String.raw`^(http[s]?:\/\/){0,1}tidsskriftet\.no(\/[0-9]+){2}\/[a-z0-9]+\/[a-z0-9\-]+`],
      "utpjournals.press": [String.raw`^(http[s]?:\/\/){0,1}utpjournals\.press\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.aanda.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?aanda\.org\/articles\/aa\/abs(\/[0-9]+){2}(\/[a-z0-9\-]+){2}\.html`],
      "www.actahort.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?actahort\.org\/books(\/[0-9]+){2}\_[0-9]+\.htm`],
      "www.advbiores.net": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?advbiores\.net\/article\.asp\?`],
      "www.aerzteblatt.de": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?aerzteblatt\.de\/[a-z]+\/archive\/article\/[0-9]+`],
      "www.aging-us.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?aging\-us\.com\/article\/[0-9]+(\/text)?`],
      "www.agriculturejournals.cz": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?agriculturejournals\.cz\/web\/pse\.htm\?`],
      "www.ahajournals.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ahajournals\.org\/doi(\/[a-z]+)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.aimsciences.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?aimsciences\.org\/article\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.aimspress.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?aimspress\.com\/article\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.ajol.info": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ajol\.info\/(\/)?index\.php\/[a-z0-9]+\/article\/view\/[0-9]+`],
      "www.ajronline.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ajronline\.org\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.ajtmh.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ajtmh\.org\/content\/journals\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.altex.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?altex\.org\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "www.americanscientist.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?americanscientist\.org\/article\/[a-z0-9\-]+`],
      "www.ams.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ams\.org\/journals\/[a-z0-9]+(\/[a-z0-9\-]+){2}`],
      "www.amsi.ge": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?amsi\.ge\/[a-z]+\/[0-9]+\/[a-z0-9\-]+\.htm`],
      "www.annualreviews.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?annualreviews\.org\/((doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+)|page\/[a-z]+\/[0-9]+\-[0-9]+)`],
      "www.archivesofmedicine.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?archivesofmedicine\.com\/medicine\/[a-z0-9\-]+`],
      "www.archivesofpathology.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?archivesofpathology\.org\/doi(\/[a-z]+)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.asianjournalofchemistry.co.in": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?asianjournalofchemistry\.co\.in\/User\/ViewFreeArticle\.aspx\?ArticleID\=`],
      "www.atlantis-press.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?atlantis\-press\.com\/journals\/[a-z]+\/[0-9]+`],
      "www.atmos-chem-phys.net": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?atmos\-chem\-phys\.net(\/[0-9]+){3}`],
      "www.atmos-meas-tech.net": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?atmos\-meas\-tech\.net(\/[0-9]+){3}`],
      "www.atsjournals.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?atsjournals\.org\/doi(\/[a-z]+)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.ayujournal.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ayujournal\.org\/article\.asp\?`],
      "www.banglajol.info": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?banglajol\.info\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "www.beilstein-journals.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?beilstein\-journals\.org\/[a-z]+\/articles(\/[0-9]+){2}`],
      "www.besjournal.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?besjournal\.com\/[a-z]+\/article\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.biochemia-medica.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?biochemia\-medica\.com\/[a-z]+\/journal(\/[0-9]+){2}\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.biogeosciences.net": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?biogeosciences\.net(\/[0-9]+){3}`],
      "www.bioinformation.net": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?bioinformation\.net\/[0-9]+\/[a-z0-9]+\.htm`],
      "www.biomolther.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?biomolther\.org\/journal\/view\.html\?`],
      "www.biorxiv.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?biorxiv\.org\/content\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.bioscience.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?bioscience\.org\/[0-9]+\/[a-z0-9]+\/[a-z]+\/[0-9]+\/list\.htm`],
      "www.biotechnologia-journal.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?biotechnologia\-journal\.org\/[a-z0-9\-]+(\,[0-9]+){4}\.html`],
      "www.birpublications.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?birpublications\.org\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.bjbms.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?bjbms\.org\/[a-z]+\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "www.bmbreports.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?bmbreports\.org\/journal\/view\.html\?doi\=10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.bmrat.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?bmrat\.org\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "www.cambridge.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?cambridge\.org\/core\/(books|journals\/[a-z\-]+\/article)\/[a-z0-9\-]+\/[a-z0-9]+`],
      "www.cancerbiomed.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?cancerbiomed\.org\/index\.php\/[a-z\-]+\/article\/view\/[0-9]+`],
      "www.cancerjournal.net": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?cancerjournal\.net\/article\.asp\?`],
      "www.carcinogenesis.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?carcinogenesis\.com\/article\.asp\?`],
      "www.ccsenet.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ccsenet\.org\/journal\/index\.php\/[a-z\-]+\/article\/view\/[0-9]+`],
      "cdc.gov": [
        String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.cdc\.gov\/[a-z]+\/volumes\/[0-9]+\/[a-z]+\/[a-z0-9]+\.htm`,
        String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.cdc\.gov\/[a-z]+\/article\/[0-9]+\/[0-9]+\/[0-9]+\-[0-9]+\_article`
      ],
      "www.cell.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?cell\.com\/[a-z\-]+\/fulltext\/[a-z0-9\(\)\-]+`],
      "www.cellphysiolbiochem.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?cellphysiolbiochem\.com\/articles\/[0-9]+`],
      "www.cfrjournal.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?cfrjournal\.com\/articles\/[a-z0-9\-]+`],
      "www.chinadoi.cn": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?chinadoi\.cn\/[a-z0-9\/\.\-]+\?doi\=10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.clinmedjournals.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?clinmedjournals\.org\/articles\/[a-z]+\/[a-z0-9\-]+\.php`],
      "www.cmaj.ca": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?cmaj\.ca\/content(\/[0-9]+){2}\/[a-z0-9\-]+`],
      "www.cochranelibrary.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?cochranelibrary\.com\/[a-z]+\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.cogentoa.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?cogentoa\.com\/article\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.colbas.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?colbas\.org\/[a-z]+\/abstracts\/[a-z0-9\-]+.pdf`],
      "www.collabra.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?collabra\.org\/article\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.cureus.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?cureus\.com\/articles\/[a-z0-9\-]+`],
      "www.degruyter.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?degruyter\.com\/((view\/[a-z]+(\/[a-z0-9\-\.]+){3}\.xml)|([a-z]+\/product\/[0-9]+))`],
      "www.deswater.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?deswater\.com\/[a-z\_]+\/vol\_[0-9]+\/[0-9\_]+\.pdf`],
      "www.dl.begellhouse.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?dl\.begellhouse\.com\/journals\/[a-z0-9\,]+\.html`],
      "www.doiserbia.nb.rs": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?doiserbia\.nb\.rs\/article\.aspx\?`],
      "www.dovepress.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?dovepress\.com\/[a-z0-9\-]+`],
      "www.e-crt.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?e\-crt\.org\/journal\/view\.php\?doi\=10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.e-jei.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?e\-jei\.org\/journal\/view\.php\?doi\=10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.eajm.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?eajm\.org\/(\/)?[a-z]+\/[a-z0-9\-]+`],
      "www.ecmjournal.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ecmjournal\.org\/papers\/[a-z0-9]+\/pdf\/[a-z0-9]+\.pdf`],
      "www.ecrjournal.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ecrjournal\.com\/articles\/[a-z0-9\-]+`],
      "www.ekoloji.com.tr": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ekoloji\.com\.tr\/[a-z0-9]+\/[0-9\-]+`],
      "www.elgaronline.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?elgaronline\.com\/view\/[a-z]+(\/[0-9]+){2}\.xml`],
      "www.elis.sk": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?elis\.sk\/index\.php\?`],
      "www.emailmeform.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?emailmeform\.com\/builder\/form\/[a-z0-9]+`],
      "www.embopress.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?embopress\.org\/doi(\/[a-z]+)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.eme.ro": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?eme\.ro\/[a-z\-]+\/[a-z]+\/[a-z0-9]+\/[a-z0-9\-\_\,]+\.pdf`],
      "www.emerald.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?emerald\.com\/[a-z]+\/content\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.eneuro.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?eneuro\.org\/content(\/[0-9]+){2}\/(?:(?!["&\'<>])\S)+`],
      "www.epj-conferences.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?epj\-conferences\.org\/articles(\/[a-z]+){2}(\/[0-9]+){2}(\/[a-z0-9\_]+){2}\.html`],
      "www.epjap.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?epjap\.org\/articles(\/[a-z]+){2}(\/[0-9]+){2}(\/[a-z0-9\_]+){2}\.html`],
      "www.escienceediting.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?escienceediting\.org\/journal\/view\.php\?doi\=10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.eurekaselect.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?eurekaselect\.com\/[0-9]+\/article`],
      "www.europeanreview.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?europeanreview\.org\/article`],
      "www.eurosurveillance.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?eurosurveillance\.org\/content\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.excli.de": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?excli\.de\/[a-z0-9]+\/[a-z0-9\_]+\.pdf`],
      "www.exeley.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?exeley\.com\/[a-z0-9\_]+\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.fasebj.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?fasebj\.org\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.frontiersin.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?frontiersin\.org\/articles\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.funpecrp.com.br": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?funpecrp\.com(\.[a-z]+)?\/[a-z]+(\/articles)?\/[a-z0-9]+\/[a-z0-9\-]+\/pdf\/[a-z0-9\-\_]+\.pdf`],
      "www.future-science.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?future\-science\.com\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.futuremedicine.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?futuremedicine\.com\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.g3journal.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?g3journal\.org\/content(\/[0-9]+){3}`],
      "www.gamtostyrimai.lt": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?gamtostyrimai\.lt\/[a-z]+\/publications(\/[a-z0-9\-\_]+){1,}`],
      "www.genetics.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?genetics\.org\/content(\/[0-9]+){3}`],
      "www.globalsciencejournals.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?globalsciencejournals\.com\/article\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.gutnliver.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?gutnliver\.org\/journal\/view\.html\?doi\=10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.haematologica.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?haematologica\.org\/content(\/[a-z]+)?(\/[0-9]+){3}`],
      "www.hanser-elibrary.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?hanser\-elibrary\.com\/doi(\/[a-z]+)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.healthaffairs.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?healthaffairs\.org\/doi(\/[a-z]+)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.hh.um.es": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?hh\.um\.es\/abstracts\/[a-z0-9\_]+(\/[0-9\_]+){2}\.htm`],
      "www.hilarispublisher.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?hilarispublisher\.com\/open\-access\/[a-z0-9\-\_]+\.pdf`],
      "www.hoajonline.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?hoajonline\.com\/[a-z]+\/[0-9\-]+(\/[0-9]+){2}`],
      "www.i-scholar.in": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?i\-scholar\.in\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "www.icevirtuallibrary.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?icevirtuallibrary\.com\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.icmp.lviv.ua": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?icmp\.lviv\.ua\/journal\/[a-z]+\.[0-9]+\/[0-9]+\/abstract\.html`],
      "www.id-press.eu": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?id\-press\.eu\/[a-z]+\/article\/view\/(?:(?!["&\'<>])\S)+`],
      "www.idoj.in": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?idoj\.in\/article\.asp\?`],
      "www.igi-global.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?igi\-global\.com\/[a-z]+\/article\/[0-9]+`],
      "www.ijbs.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ijbs\.com\/[a-z0-9]+\.htm`],
      "www.ijcm.org.in": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ijcm\.org\.in\/article\.asp\?`],
      "www.ijcmas.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ijcmas\.com\/abstractview\.php\?`],
      "www.ijdb.ehu.es": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ijdb\.ehu\.es\/web\/paper\.php\?doi\=`],
      "www.ijmr.org.in": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ijmr\.org\.in\/article\.asp\?`],
      "www.ijofo.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ijofo\.org\/article\.asp\?`],
      "www.ijri.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ijri\.org\/article\.asp\?`],
      "www.ijstemcell.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ijstemcell\.com\/journal\/view\.html\?`],
      "www.ijtrichology.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ijtrichology\.com\/article\.asp\?`],
      "www.inderscience.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?inderscience\.com\/(storage\/[a-z0-9]+\.pdf|offer\.php\?id\=)`],
      "www.indianjcancer.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?indianjcancer\.com\/article\.asp\?`],
      "www.indianjournals.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?indianjournals\.com\/[a-z]+\.aspx\?`],
      "www.indianjurol.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?indianjurol\.com\/article\.asp\?`],
      "www.ingentaconnect.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ingentaconnect\.com\/(openurl|content)`],
      "www.int-res.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?int\-res\.com\/abstracts\/[a-z]+(\/[a-z0-9\-]+){2}`],
      "www.intechopen.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?intechopen\.com\/books\/[a-z0-9\/\-]+`],
      "www.intlpress.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?intlpress\.com(\/[a-z]+){1,}(\/[0-9]+){1,}`],
      "www.iosrjournals.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?iosrjournals\.org(\/[a-z0-9\-]+){1,}\.pdf`],
      "www.isaacpub.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?isaacpub\.org(\/[a-z]+){2}\/[a-z0-9\_]+\.pdf`],
      "www.isr-publications.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?isr\-publications\.com\/[a-z]+\/[a-z0-9\-]+`],
      "www.japsonline.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?japsonline\.com\/abstract\.php\?article\_id\=`],
      "www.jbc.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jbc\.org\/content(\/[0-9\-]+){3}`],
      "www.jbiopharm.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jbiopharm\.com`],
      "www.jbmethods.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jbmethods\.org\/[a-z]+\/article\/view\/[0-9]+`],
      "www.jcancer.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jcancer\.org\/[a-z0-9]+\.htm`],
      "www.jclmm.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jclmm\.com\/[a-z0-9\/]+\.pdf`],
      "www.jcpjournal.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jcpjournal\.org\/journal\/view\.html\?`],
      "www.jgld.ro": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jgld\.ro\/[a-z0-9\/\.]+`],
      "www.jimmunol.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jimmunol\.org\/content(\/[0-9]+){3}`],
      "www.jkcs.or.kr": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jkcs\.or\.kr\/journal\/view\.php\?doi\=10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.jle.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jle\.com\/[a-z0-9\-\_\/]+\/article\.phtml`],
      "www.jlr.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jlr\.org\/content(\/[0-9]+){3}`],
      "www.jmolecularsignaling.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jmolecularsignaling\.com\/articles\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.jneurosci.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jneurosci\.org\/content(\/[0-9]+){3}`],
      "www.jnmjournal.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jnmjournal\.org\/journal\/view\.html\?doi\=10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.jocmr.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jocmr\.org\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "www.jomfp.in": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jomfp\.in\/article\.asp\?`],
      "www.jospi.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jospi\.org\/article\/[a-z0-9\-]+`],
      "www.journalofadvertisingresearch.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?journalofadvertisingresearch\.com\/content(\/[0-9]+){3}`],
      "www.journalrcr.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?journalrcr\.org\/article\.asp\?`],
      "www.journals.uchicago.edu": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?journals\.uchicago\.edu\/doi\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.journalslibrary.nihr.ac.uk": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?journalslibrary\.nihr\.ac\.uk\/[a-z]+\/[a-z0-9]+\/\#\/abstract`],
      "www.jove.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jove\.com\/video\/[0-9]+\/[a-z0-9\-]+`],
      "www.jpatholtm.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jpatholtm\.org\/journal\/view\.php\?doi\=10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.jstage.jst.go.jp": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jstage\.jst\.go\.jp\/article\/[a-z]+(\/[0-9]+){2}\/[0-9\_]+\/\_article`],
      "www.jstor.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?jstor\.org\/stable\/[0-9]+`],
      "www.kaleidoscopehistory.hu": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?kaleidoscopehistory\.hu\/index\.php\?`],
      "www.karger.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?karger\.com\/article\/[a-z]+\/[0-9]+`],
      "www.liebertpub.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?liebertpub\.com\/doi(\/[a-z]+)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.life-science-alliance.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?life\-science\-alliance\.org\/content(\/[0-9]+){2}\/[a-z0-9]+`],
      "www.lifescied.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?lifescied\.org\/doi(\/[a-z]+)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.lifescienceglobal.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?lifescienceglobal\.com\/journals\/[a-z0-9\/\-]+`],
      "www.longdom.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?longdom\.org\/open\-access\/[a-z0-9\-\.]+\.pdf`],
      "www.mcponline.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?mcponline\.org\/content(\/[0-9]+){2,}`],
      "www.mcser.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?mcser\.org\/journal\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "www.mdpi.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?mdpi\.com\/[0-9]+\-[a-z0-9]+(\/[0-9]+){3}`],
      "www.meajo.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?meajo\.org\/article\.asp\?`],
      "www.medicinaoral.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?medicinaoral\.com(\/[a-z0-9]+){2,}\/[0-9]+\.pdf`],
      "www.medrxiv.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?medrxiv\.org\/content\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.medsci.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?medsci\.org\/[a-z0-9]+\.htm`],
      "www.medscimonit.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?medscimonit\.com\/abstract\/index\/[a-z]+\/[0-9]+`],
      "www.metrology-journal.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?metrology\-journal\.org\/articles(\/[a-z]+){1,}(\/[0-9]+){1,}(\/[a-z0-9]+){1,}\.html`],
      "www.microbiologyresearch.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?microbiologyresearch\.org\/content\/journal\/[a-z]+\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.mii.lt": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?mii\.lt\/informatica\/htm\/[a-z0-9]+\.htm`],
      "www.mitpressjournals.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?mitpressjournals\.org\/doi(\/[a-z]+)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.mjms.mk": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?mjms\.mk\/[a-z]+\/[a-z0-9\_]+\/(?:(?!["&\'<>])\S)+`],
      "www.mmnp-journal.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?mmnp\-journal\.org\/articles(\/[a-z]+){1,}(\/[0-9]+){1,}(\/[a-z0-9]+){1,}\.html`],
      "www.molbiolcell.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?molbiolcell\.org\/doi(\/[a-z]+)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.molcells.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?molcells\.org\/journal\/view\.html\?doi\=`],
      "www.mrforum.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?mrforum\.com\/product\/(?:(?!["&\'<>])\S)+`],
      "www.msmonographs.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?msmonographs\.org\/article\.asp\?`],
      "www.mvm.fink.rs": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?mvm\.fink\.rs\/journal\/archive\/[0-9]+\/[a-z0-9]+\/[a-z0-9\-]+\.html`],
      "www.najms.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?najms\.org\/article\.asp\?`],
      "www.nature.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?nature\.com\/(news|articles)\/(?:(?!["&\'<>])\S)+`],
      "www.ncbi.nlm.nih.gov": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ncbi\.nlm\.nih\.gov\/pmc\/(journals|articles)\/[a-z0-9]+`],
      "www.nejm.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?nejm\.org\/doi(\/[a-z]+)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.nepjol.info": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?nepjol\.info\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "www.notulaebiologicae.ro": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?notulaebiologicae\.ro\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "www.notulaebotanicae.ro": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?notulaebotanicae\.ro\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "www.nrcresearchpress.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?nrcresearchpress\.com\/doi(\/[a-z]+)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.nrronline.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?nrronline\.org\/article\.asp\?`],
      "www.ntno.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ntno\.org\/[a-z0-9]+\.htm`],
      "www.oatext.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?oatext\.com\/[a-z0-9\-]+\.php`],
      "www.omicsonline.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?omicsonline\.org\/(?:(?!["&\'<>])\S)+\.(php|html)`],
      "www.omjournal.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?omjournal\.org\/articleDetails\.aspx\?`],
      "www.oncotarget.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?oncotarget\.com\/article\/[0-9]+\/[a-z]+`],
      "www.orientjchem.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?orientjchem\.org\/[a-z0-9]+\/[a-z0-9\-]+`],
      "www.orientjphysicalsciences.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?orientjphysicalsciences\.org\/[a-z0-9]+\/[a-z0-9\-]+`],
      "www.osapublishing.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?osapublishing\.org\/[a-z]+\/abstract\.cfm\?`],
      "www.oxfordbibliographies.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?oxfordbibliographies\.com\/view\/document(\/[a-z0-9\-]+){2,}\.xml`],
      "www.oxfordhandbooks.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?oxfordhandbooks\.com\/view\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.pagepress.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?pagepress\.org\/journals\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "www.panafrican-med-journal.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?panafrican\-med\-journal\.com\/content\/article(\/[0-9]+){2,}`],
      "www.pdcnet.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?pdcnet\.org\/[a-z]+\/content\/[a-z0-9\_]+`],
      "www.peertechz.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?peertechz\.com\/articles\/[a-z0-9\-]+\.php`],
      "www.phcog.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?phcog\.com\/article\.asp\?`],
      "www.phcogfirst.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?phcogfirst\.com\/article\/[0-9]+`],
      "www.physiology.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?physiology\.org\/doi(\/[a-z]+)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.plantcell.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?plantcell\.org\/content(\/[a-z0-9]+){1,}`],
      "www.plantphysiol.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?plantphysiol\.org\/content(\/[a-z0-9]+){1,}`],
      "www.pnas.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?pnas\.org\/content(\/[a-z0-9]+){1,}`],
      "www.preprints.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?preprints\.org\/[a-z]+\/[0-9\.]+\/[a-z0-9]+`],
      "www.psychiatryinvestigation.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?psychiatryinvestigation\.org\/journal\/view\.php\?doi\=10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.pubhort.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?pubhort\.org\/[a-z]+(\/[0-9]+){2}\/[a-z0-9]+\.htm`],
      "www.publish.csiro.au": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?publish\.csiro\.au\/[a-z]+\/[a-z0-9]+`],
      "www.radcliffecardiology.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?radcliffecardiology\.com\/articles\/[a-z0-9\-]+`],
      "www.rcpjournals.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?rcpjournals\.org\/content\/[a-z]+(\/[0-9]+){1,}`],
      "www.reed.es": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?reed\.es\/[a-z0-9\%\-]+`],
      "www.repo.uni-hannover.de": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?repo\.uni\-hannover\.de\/handle(\/[0-9]+){2}`],
      "www.researchgate.net": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?researchgate\.net\/publication\/[0-9]+`],
      "www.rug.nl": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?rug\.nl(\/[a-z]+){1,}\/publications\/[a-z0-9\-\%\(\)]+\.html`],
      "www.scholink.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?scholink\.org\/[a-z]+\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "www.schweizerbart.de": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?schweizerbart\.de\/papers\/[a-z]+\/detail(\/[0-9]+){2}\/[a-z0-9\_]+`],
      "www.scielo.br": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?scielo\.br\/scielo\.php\?`],
      "www.sciencedirect.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?sciencedirect\.com\/science\/article(\/[a-z]+)*\/[a-z0-9]+`],
      "www.sciencedomain.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?sciencedomain\.org\/abstract\/[0-9]+`],
      "sciencemag.org": [String.raw`^(http[s]?:\/\/){0,1}[a-z0-9\.\-]+\.sciencemag\.org\/[a-z]+\/[a-z0-9\-\_\/\.]+`],
      "www.scienceopen.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?scienceopen\.com\/document\?id\=`],
      "www.sciencepubco.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?sciencepubco\.com\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "www.scientific.net": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?scientific\.net\/[a-z]+\.[a-z0-9\-\.]+`],
      "www.sciknow.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?sciknow\.org\/article\/detail\/id\/[0-9]+`],
      "www.scirp.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?scirp\.org\/journal\/paperinformation\.aspx\?paperid\=`],
      "www.scitechnol.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?scitechnol\.com\/[a-z0-9\-]+\.php`],
      "www.scopemed.org": [],
      "www.seefor.eu": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?seefor\.eu\/archive\/[0-9]+(\/[a-z0-9\-]+){1,}\.html`],
      "www.spandidos-publications.com": [
        String.raw`^(http[s]?:\/\/){0,1}(www\.)?spandidos\-publications\.com\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`,
        String.raw`^(http[s]?:\/\/){0,1}(www\.)?spandidos\-publications\.com\/[a-z]+(\/[0-9]+){3}`
      ],
      "www.spiedigitallibrary.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?spiedigitallibrary\.org\/[a-z0-9\/\-]+\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+\.short`],
      "www.springerlink.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?springerlink\.com\/index\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.ssbfnet.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ssbfnet\.com\/[a-z]+\/index\.php\/[a-z]+\/article\/view\/[0-9]+`],
      "www.tandfonline.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?tandfonline\.com\/doi(\/[a-z]+)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.taylorfrancis.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?taylorfrancis\.com\/books(\/[a-z]+)?\/[0-9]+`],
      "www.termedia.pl": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?termedia\.pl\/[a-z0-9\-\,]+\.html`],
      "www.the-cryosphere.net": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?the\-cryosphere\.net(\/[0-9]+){3}`],
      "www.thieme-connect.de": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?thieme\-connect\.de(\/[a-z]+){3}\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.thno.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?thno\.org\/[a-z0-9]+\.htm`],
      "www.tobaccoinduceddiseases.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?tobaccoinduceddiseases\.org\/[a-z0-9\-\,]+\.html`],
      "www.toxicolres.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?toxicolres\.org\/journal\/view\.html\?doi\=`],
      "www.ukm.my": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?ukm\.my\/[a-z]+\/pdf\_files\/[a-z0-9\/\%\-]+\.pdf`],
      "www.vbripress.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?vbripress\.com\/[a-z]+\/articles\/details\/[0-9]+`],
      "www.veterinaryworld.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?veterinaryworld\.org\/vol\.[0-9]+\/[a-z0-9\/\%\-]+\.html`],
      "www.who.int": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?who\.int\/bulletin\/volumes(\/[0-9]+){1,}\-[0-9]+\.pdf`],
      "www.witpress.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?witpress\.com\/[a-z]+\/[a-z0-9\-]+(\/[0-9]+){1,}`],
      "www.wjgnet.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?wjgnet\.com\/[0-9]+\-[0-9]+\/full\/v[0-9]+\/i[0-9]+\/[0-9]+\.htm`],
      "www.worldscientific.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?worldscientific\.com\/doi(\/[a-z]+)?\/10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'<>])\S)+`],
      "www.worldwidejournals.com": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?worldwidejournals\.com\/[a-z0-9\-]+\/file\.php`],
      "zenodo.org": [String.raw`^(http[s]?:\/\/){0,1}(www\.)?zenodo\.org\/record\/[0-9]+`],
    },

    getDomainList: function () {
      return Object.keys(Domains._allowedDomains);
    },

    extractDomainsFromUrl: function (url) {
      const match = url.match(/(:\/\/)[a-z0-9\-]+(\.[a-z0-9\-]+)+(?=(\:)?\/)/gi);
      let domains = [];
      if (match !== null && match.length > 0 && 'string' === typeof match[0] && match[0].length > 3) {
        try {
          const domain = match[0].split('://')[1].toLowerCase();
          domains.push(domain);
          const componentDelimiter = '.';
          let domainComponents = domain.split(componentDelimiter);
          if (domainComponents.length > 2) {
            domainComponents.shift();
            domains.push(domainComponents.join(componentDelimiter));
          }
        } catch (e) {}
      }
      return domains;
    },

    validate: function (url) {
      const domains = Domains.extractDomainsFromUrl(url);
      for (let i = 0; i < domains.length; i++) {
        if (Domains.getDomainList().includes(domains[i])) {
          for (let j = 0; j < Domains._allowedDomains[domains[i]].length; j++) {
            if ((new RegExp(Domains._allowedDomains[domains[i]][j], 'gi')).test(url)) {
              return true;
            }
          }
          if (Domains._allowedDomains[domains[i]].length === 0) {
            return true;
          }
        }
      }
      return false;
    }
  };
  return Domains;
}));
